version: '2.1'

services:
  sptribs-case-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/spring-boot/template
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT
  ccd-case-document-am-api:
    image: "${CCD_CASE_DOCUMENT_AM_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/case-document-am-api:${CCD_CASE_DOCUMENT_AM_API_TAG:-latest}"
    environment:
      CASE_DOCUMENT_AM_API_S2S_SECRET: "${IDAM_KEY_CASE_DOCUMENT}"
      CASE_DOCUMENT_S2S_AUTHORISED_SERVICES: ccd_case_document_am_api,ccd_gw,xui_webapp,ccd_data,bulk_scan_processor
      IDAM_API_URL: http://idam-api:5000
      IDAM_OIDC_URL: http://idam-api:5000
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      DM_STORE_BASE_URL: http://dm-store:8080
      CCD_DATA_STORE_API_BASE_URL: http://ccd-data-store-api:4452
      REFORM_SERVICE_NAME: ccd-case-document-am-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      DOCUMENT_TTL: 3600000
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      # JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
    ports:
      - 4455:4455
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # 5005:5005
    depends_on:
      - ccd-data-store-api
      - dm-store
