version: '2.1'

services:
  sptribs-case-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/spring-boot/template
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT

  ccpay-notifications-service-db:
    container_name: ccpay-notifications-service-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=notifications
      - POSTGRES_PASSWORD=notifications
      - POSTGRES_DB=notifications
    ports:
      - 5182:5433
    volumes:
      - ccpay-notifications-service-db-data:/var/lib/postgresql/data
