package uk.gov.hmcts.sptribs.notification;

public enum TemplateName {
    RESPONDENT_SOLICITOR_HAS_NOT_RESPONDED,
    APPLICATION_RECEIVED,
    APPLICATION_NEW_ORDER_ISSUED,
    CASE_REINSTATED_EMAIL,
    CASE_REINSTATED_POST,
    DECISION_ISSUED_EMAIL,
    DECISION_ISSUED_POST,
    CASE_STAYED_EMAIL,
    CASE_STAYED_POST,
    CASE_UNSTAYED_EMAIL,
    CASE_UNSTAYED_POST,
    TEST_TEMPLATE,
    CASE_ISSUED_CITIZEN_EMAIL,
    CASE_ISSUED_CITIZEN_POST,
    CASE_ISSUED_RESPONDENT_EMAIL,
    LISTING_UPDATED_CITIZEN_EMAIL,
    LISTING_UPDATED_CITIZEN_POST,
    LISTING_CREATED_CITIZEN_EMAIL,
    LISTING_CREATED_CITIZEN_POST
}
