apiVersion: v2
appVersion: "1.0"
description: A Helm chart for sptribs-case-api App
name: sptribs-case-api
home: https://github.com/hmcts/sptribs-case-api
version: 0.0.94
maintainers:
  - name: HMCTS sptribs team
dependencies:
  - name: java
    version: 5.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 8.0.29
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - ccd-idam-pr
  - name: xui-webapp
    version: ~1.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
  - name: xui-mo-webapp
    version: ~1.1.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-mo-webapp.enabled
  - name: aac-manage-case-assignment
    version: ~0.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: aac-manage-case-assignment.enabled
  - name: idam-pr
    version: 2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
  - name: ccd-case-document-am-api
    version: 1.7.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd-case-document-am-api.enabled
  - name: em-ccdorc
    version: 2.0.10
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: em-ccdorc.enabled
  - name: em-stitching
    version: 1.0.31
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: em-stitching.enabled
    #Work Allocation
#  - name: camunda-bpm
#    version: 0.0.47
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#  - name: wa-task-management-api
#    version: 0.0.52
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#  - name: wa-task-monitor
#    version: 0.0.35
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#  - name: wa-case-event-handler
#    version: 0.0.40
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#  - name: wa-workflow-api
#    version: 0.0.41
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#    #Initiation
#  - name: wa-task-batch-service
#    version: ~0.0.16
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    alias: wa-initiation-batch
#    condition: wa.taskBatchCron.enabled
#    #Reconfiguration
#  - name: wa-task-batch-service
#    version: ~0.0.16
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    alias: wa-reconfiguration-batch
#    condition: wa.reconfigurationBatchCron.enabled
#    #Termination
#  - name: wa-task-batch-service
#    version: ~0.0.16
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    alias: wa-termination-batch
#    condition: wa.terminationBatchCron.enabled
#  - name: wa-message-cron-service
#    version: ~0.0.3
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#  - name: ccd-message-publisher
#    version: ~0.1.7
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: wa.enabled
#  - name: servicebus
#    version: 1.0.4
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: servicebus.enabled
#  - name: am-org-role-mapping-service
#    version: 0.0.63
#    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
#    condition: am-org-role-mapping-service.enabled
