apiVersion: v2
appVersion: "1.0"
description: A Helm chart for sptribs-case-api App
name: sptribs-case-api
home: https://github.com/hmcts/sptribs-case-api
version: 0.0.93
maintainers:
  - name: HMCTS sptribs team
dependencies:
  - name: java
    version: 5.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: sptribs-frontend
    version: 0.0.33
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: sptribs-frontend.enabled
  - name: idam-pr
    version: 2.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
