servicebus:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-asb
  resourceGroup: sptribs-aso-preview-rg
  sbNamespace: sptribs-servicebus-preview
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
        requiresSession: true

postgres:

wa:
  enabled: true
  postgresql:
    enabled: false

ccd-message-publisher:
  java:
    ingressHost: ccd-message-publisher-${SERVICE_FQDN}
    releaseNameOverride: ${SERVICE_NAME}-ccd-message-publisher
    secrets:
      SERVICE_BUS_CONNECTION_STRING:
        secretRef: sptribs-sb-preview
        key: connectionString
      DATA_STORE_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: false
    environment:
      DATA_STORE_DB_HOST: sptribs-preview.postgres.database.azure.com
      DATA_STORE_DB_NAME: "pr-${CHANGE_ID}-data-store"
      DATA_STORE_DB_USERNAME: hmcts
      DATA_STORE_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      CCD_CASE_EVENTS_DESTINATION: "${SERVICE_NAME}-servicebus-ccd-events"