# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CHANGE_ID: ${CHANGE_ID}
  keyVaults:
    sptribs:
      secrets:
        - name: app-insights-instrumentation-key-preview
          alias: app-insights-instrumentation-key
        - name: app-insights-connection-string-preview
          alias: app-insights-connection-string
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY_1
        - name: s2s-case-api-secret
          alias: S2S_SECRET
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-systemupdate-username
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-systemupdate-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: launchdarkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY

sptribs-frontend:
  enabled: true
  nodejs:
    registerAdditionalDns:
      enabled: false
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-frontend
    image: hmctspublic.azurecr.io/sptribs/frontend:latest #pr-xxxx
    ingressHost: frontend-${SERVICE_FQDN}
    environment:
      CCD_URL: http://{{ .Release.Name }}-ccd-data-store-api
      SKIP_DIV_CASE_CHECK: true

idam-pr:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-idam-pr
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
    XUIMO:
      - https://xui-mo-${SERVICE_FQDN}/oauth2/callback
