spring:
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  messages:
    encoding: ISO-8859-1
  autoconfigure:
    exclude:
      - com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration
  datasource:
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jms:
    servicebus:
      enabled: false

s2s:
  stub: true

core_case_data:
  api:
    url: http://localhost:4012
  search:
    page_size: 100
