create table if not exists case_documents (
  id bigint generated by default as identity primary key,
  case_reference_number bigint not null references ccd.case_data(reference) on delete cascade,
  saved_at timestamp not null default current_timestamp,
  document_url varChar(200) not null,
  document_binary_url varChar(200) not null unique,
  document_filename varChar(200) not null,
  document_type_name varChar(100),
  case_document_type_id BIGINT NOT NULL REFERENCES case_document_types(id),
  updated_at timestamp default current_timestamp
);
