alter table statements add column if not exists id_bigint bigint generated by default as identity;

update statements
set id_bigint = default
where id_bigint is null;

alter table statements alter column id_bigint set not null;

alter table statements drop constraint if exists statements_pkey;

alter table statements drop column if exists id;

alter table statements rename column id_bigint to id;

alter table statements add primary key (id);
